dist: trusty
sudo: false

language:
  - cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

  - os: osx

install:
  - ./ci/install-${TRAVIS_OS_NAME}.sh

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls

script: ./ci/travis.sh

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - g++-4.9
    - clang-3.9

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false