sudo: false

language:
- cpp

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake']
    packages: ['clang-3.7', 'cmake']

before_install:
- pip install --user cpp-coveralls

script:
- cmake -H. -Bbuild
- cd build/test
- cmake --build .
- ctest

after_success:
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false