dist: trusty
sudo: false

language:
- cpp

matrix:
  include:
  # works on Trusty
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
    env:
    - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

  # works on Trusty
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  - os: osx
    compiler: clang
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"


before_install:
- eval "${MATRIX_EVAL}"
- pip install --user cpp-coveralls

script:
- cmake -H. -Bbuild
- cd build/test
- cmake --build .
- ctest --verbose

after_success:
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false